[workspace]
members = [
    "crates/executor",
    "crates/mate",
    "crates/scheduler",
]
default-members = ["crates/mate"]
resolver = "1"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
redis = "0.27"
tokio = "1"

mate = { path = "./crates/mate" }
